version: '3'
services:
  postgres:
    image: postgres:10
    restart: always
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
      - POSTGRES_USER=test
    #volumes:
      #- ./postgres/:/var/lib/postgresql/data/
    ports:
      - 127.0.0.1:5445:5432